#!/bin/bash

# Empêche la faute de frappe "recontre" à la place de "rencontre".

if [ $(grep --exclude-dir={.git,hooks} -nr recontre | wc -l) -gt 0 ]
then
    echo "You're committing a spelling mistake !"
    grep --color --exclude-dir={.git,hooks} -nr recontre
    exit 1
fi
